name: Generate Docs

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.json -d docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy-key: ${{ secrets.GH_PAGES_SSH_KEY }}
          publish_dir: ./docs
          publish_branch: gh-pages
